Saved both raw and processed textract output
datamade/lm10 pull request #12
Opened 2022-03-18 12:46 UTC by antidipyramid

## Overview

Textract's processed output seems to be missing some form key-value data from the PDF. This PR saves both the processed and raw response from Textract to help debug the issue.

`scripts/process_pdfs.py` generates two files for each PDF: `[pdf_file_name]_processed.json` and `[pdf_file_name]_raw.json`.

## Testing Instructions

- Navigate to `final/` and examine the script's output

Handles #10

2022-03-18 13:42 UTC, fgregg requested changes

2022-03-18 13:42 UTC, fgregg commented on scripts/process_pdfs.py
> +        with open(f'final/{pdf_name}_processed.json', 'w') as output:
can we write these to an intermediate directory, and then we can keep the sames without the _raw or _processed suffixes.

2022-03-18 15:18 UTC, antidipyramid commented on scripts/process_pdfs.py
> +        with open(f'final/{pdf_name}_processed.json', 'w') as output:
Do we want a these files inside of `final/` (i.e. `final/raw/` and `final/processed/`)?

Or we could put a directory at the root similar to `images/` and store the raw files there?

2022-03-18 15:22 UTC, fgregg commented on scripts/process_pdfs.py
> +        with open(f'final/{pdf_name}_processed.json', 'w') as output:
> Or we could put a directory at the root similar to images/ and store the raw files there?

yup!

2022-03-18 17:52 UTC, fgregg requested changes
just a small changes to write more directly, and do pretty printing

2022-03-18 17:52 UTC, fgregg commented on scripts/process_pdfs.py
> +            output.write(json.dumps(all_blocks))
```suggestion
            json.dump(all_blocks, output, indent=4)
```

2022-03-18 17:52 UTC, fgregg commented on scripts/process_pdfs.py
>              output.write(json.dumps(form_key_values))
```suggestion
            json.dump(form_key_values, output, indent=4)
```

2022-03-18 23:11 UTC, fgregg requested changes
a more direct way to write output and pretty printing

2022-03-21 12:30 UTC, fgregg approved these changes

2022-03-21 12:31 UTC, fgregg commented
thanks @antidipyramid! I'll handle the merge conflict!

2022-03-21 13:20 UTC, merged